### ISSUE TITLE
[DOC] Which version of the SQLCipher?

### ISSUE THREAD

**Issue by 7934345** [linchenhuicn/react-native-sqlcipher#2]
Please add SQLCipher's version in the README

**Comment by 7934345** [comment]
And andpor/react-native-sqlite-storage #5.0 has released and is there any code that can merge from there?

**Comment by linchenhuicn** [comment]
SQLCipher #4.3.0

**Comment by MebDevelop** [comment]
@linchenhuicn Can you upgrade this package to library support andpor/react-native-sqlite-storage #5.0?
